services:
  app:
    image: ${DOCKER_REPO}/${APP_IMAGE_NAME}
    entrypoint: ["npm"]
    command: ${APP_COMMAND}
    volumes:
      - type: bind
        source: "../src/app/"
        target: "/home/node/site"
    networks:
      - shared
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}"]
      interval: 20s
      timeout: 5s
      retries: 3
  test_client:
    image: ${DOCKER_REPO}/${TEST_CLIENT_IMAGE_NAME}
    entrypoint: ["npm"]
    depends_on:
      - app
    volumes:
      - type: bind
        source: "../src/test/"
        target: "/home/node/site"
    networks:
      - shared

networks:
  shared:
    driver: bridge
